In [14]:
!pip install numpy

<h3>NumPy - Ndarray Object</h3><br>
    The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

Every item in an ndarray takes the same size of block in the memory. Each element in ndarray is an object of data-type object (called dtype).


<b>numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)</b>

<table class="table table-bordered">
<tbody><tr>

<th style="text-align:center;">Parameter &amp; Description</th>
</tr>
<tr>

<td><p><b>object</b></p>
<p>Any object exposing the array interface method returns an array, or any (nested) sequence.</p>
</td>
</tr>
<tr>

<td><p><b>dtype</b></p>
<p>Desired data type of array, optional</p>
</td>
</tr>
<tr>

<td><p><b>copy</b></p>
<p>Optional. By default (true), the object is copied</p>
</td>
</tr>
<tr>

<td><p><b>order</b></p>
<p>C (row major) or F (column major) or A (any) (default)</p>
</td>
</tr>
<tr>

<td><p><b>subok</b></p>
<p>By default, returned array forced to be a base class array. If true, sub-classes passed through</p>
</td>
</tr>
<tr>

<td><p><b>ndmin</b></p>
<p>Specifies minimum dimensions of resultant array</p>
</td>
</tr>
</tbody></table>

<dl><dd><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle A={\begin{bmatrix}a_{11}&amp;a_{12}&amp;a_{13}\\a_{21}&amp;a_{22}&amp;a_{23}\end{bmatrix}}}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <mi>A</mi>
        <mo>=</mo>
        <mrow class="MJX-TeXAtom-ORD">
          <mrow>
            <mo>[</mo>
            <mtable rowspacing="4pt" columnspacing="1em">
              <mtr>
                <mtd>
                  <msub>
                    <mi>a</mi>
                    <mrow class="MJX-TeXAtom-ORD">
                      <mn>11</mn>
                    </mrow>
                  </msub>
                </mtd>
                <mtd>
                  <msub>
                    <mi>a</mi>
                    <mrow class="MJX-TeXAtom-ORD">
                      <mn>12</mn>
                    </mrow>
                  </msub>
                </mtd>
                <mtd>
                  <msub>
                    <mi>a</mi>
                    <mrow class="MJX-TeXAtom-ORD">
                      <mn>13</mn>
                    </mrow>
                  </msub>
                </mtd>
              </mtr>
              <mtr>
                <mtd>
                  <msub>
                    <mi>a</mi>
                    <mrow class="MJX-TeXAtom-ORD">
                      <mn>21</mn>
                    </mrow>
                  </msub>
                </mtd>
                <mtd>
                  <msub>
                    <mi>a</mi>
                    <mrow class="MJX-TeXAtom-ORD">
                      <mn>22</mn>
                    </mrow>
                  </msub>
                </mtd>
                <mtd>
                  <msub>
                    <mi>a</mi>
                    <mrow class="MJX-TeXAtom-ORD">
                      <mn>23</mn>
                    </mrow>
                  </msub>
                </mtd>
              </mtr>
            </mtable>
            <mo>]</mo>
          </mrow>
        </mrow>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle A={\begin{bmatrix}a_{11}&amp;a_{12}&amp;a_{13}\\a_{21}&amp;a_{22}&amp;a_{23}\end{bmatrix}}}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/0d2606537373aed9f7c6240cc6c94efcce12c53a" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -2.505ex; width:22.011ex; height:6.176ex;" alt="{\displaystyle A={\begin{bmatrix}a_{11}&amp;a_{12}&amp;a_{13}\\a_{21}&amp;a_{22}&amp;a_{23}\end{bmatrix}}}"></span></dd></dl>


<div>
<table class="wikitable" style="text-align:center; width:250px">
<caption>Row-major order  (lexographical access order)
</caption>
<tbody><tr>
<th>Address
</th>
<th>Access
</th>
<th>Value
</th></tr>
<tr>
<th>0
</th>
<td><code>A[0][0]</code>
</td>
<td><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle a_{11}}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <msub>
          <mi>a</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mn>11</mn>
          </mrow>
        </msub>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle a_{11}}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/411c26881c752d514e61bfdd5eb8463c6e808202" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -0.671ex; width:3.106ex; height:2.009ex;" alt="a_{11}"></span>
</td></tr>
<tr>
<th>1
</th>
<td><code>A[0][1]</code>
</td>
<td><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle a_{12}}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <msub>
          <mi>a</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mn>12</mn>
          </mrow>
        </msub>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle a_{12}}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/e062aea942fa88bbd0aa72d26f8fc011b323bf5e" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -0.671ex; width:3.106ex; height:2.009ex;" alt="a_{12}"></span>
</td></tr>
<tr>
<th>2
</th>
<td><code>A[0][2]</code>
</td>
<td><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle a_{13}}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <msub>
          <mi>a</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mn>13</mn>
          </mrow>
        </msub>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle a_{13}}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/de4f86c305ff1b04fabb1cddcedd192853d6815c" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -0.671ex; width:3.106ex; height:2.009ex;" alt="a_{{13}}"></span>
</td></tr>
<tr>
<th>3
</th>
<td><code>A[1][0]</code>
</td>
<td><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle a_{21}}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <msub>
          <mi>a</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mn>21</mn>
          </mrow>
        </msub>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle a_{21}}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/372531d1d09885784f3430660f8654b0d48eb394" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -0.671ex; width:3.106ex; height:2.009ex;" alt="a_{21}"></span>
</td></tr>
<tr>
<th>4
</th>
<td><code>A[1][1]</code>
</td>
<td><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle a_{22}}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <msub>
          <mi>a</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mn>22</mn>
          </mrow>
        </msub>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle a_{22}}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/f7a66fac4dcd116c0dca38bd6cd9a805f62b69f4" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -0.671ex; width:3.106ex; height:2.009ex;" alt="a_{{22}}"></span>
</td></tr>
<tr>
<th>5
</th>
<td><code>A[1][2]</code>
</td>
<td><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle a_{23}}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <msub>
          <mi>a</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mn>23</mn>
          </mrow>
        </msub>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle a_{23}}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/e214e4d1b4dcc0f3909e915fd69012c5bd1b7b7b" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -0.671ex; width:3.106ex; height:2.009ex;" alt="{\displaystyle a_{23}}"></span>
</td></tr></tbody></table>

<table class="wikitable" style="text-align:center; width:250px">
<caption>Column-major order  (colexographical access order)
</caption>
<tbody><tr>
<th>Address
</th>
<th>Access
</th>
<th>Value
</th></tr>
<tr>
<th>0
</th>
<td><code>A[0][0]</code>
</td>
<td><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle a_{11}}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <msub>
          <mi>a</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mn>11</mn>
          </mrow>
        </msub>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle a_{11}}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/411c26881c752d514e61bfdd5eb8463c6e808202" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -0.671ex; width:3.106ex; height:2.009ex;" alt="a_{11}"></span>
</td></tr>
<tr>
<th>1
</th>
<td><code>A[1][0]</code>
</td>
<td><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle a_{21}}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <msub>
          <mi>a</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mn>21</mn>
          </mrow>
        </msub>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle a_{21}}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/372531d1d09885784f3430660f8654b0d48eb394" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -0.671ex; width:3.106ex; height:2.009ex;" alt="a_{21}"></span>
</td></tr>
<tr>
<th>2
</th>
<td><code>A[0][1]</code>
</td>
<td><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle a_{12}}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <msub>
          <mi>a</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mn>12</mn>
          </mrow>
        </msub>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle a_{12}}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/e062aea942fa88bbd0aa72d26f8fc011b323bf5e" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -0.671ex; width:3.106ex; height:2.009ex;" alt="a_{12}"></span>
</td></tr>
<tr>
<th>3
</th>
<td><code>A[1][1]</code>
</td>
<td><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle a_{22}}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <msub>
          <mi>a</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mn>22</mn>
          </mrow>
        </msub>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle a_{22}}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/f7a66fac4dcd116c0dca38bd6cd9a805f62b69f4" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -0.671ex; width:3.106ex; height:2.009ex;" alt="a_{{22}}"></span>
</td></tr>
<tr>
<th>4
</th>
<td><code>A[0][2]</code>
</td>
<td><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle a_{13}}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <msub>
          <mi>a</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mn>13</mn>
          </mrow>
        </msub>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle a_{13}}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/de4f86c305ff1b04fabb1cddcedd192853d6815c" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -0.671ex; width:3.106ex; height:2.009ex;" alt="a_{{13}}"></span>
</td></tr>
<tr>
<th>5
</th>
<td><code>A[1][2]</code>
</td>
<td><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none;"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="{\displaystyle a_{23}}">
  <semantics>
    <mrow class="MJX-TeXAtom-ORD">
      <mstyle displaystyle="true" scriptlevel="0">
        <msub>
          <mi>a</mi>
          <mrow class="MJX-TeXAtom-ORD">
            <mn>23</mn>
          </mrow>
        </msub>
      </mstyle>
    </mrow>
    <annotation encoding="application/x-tex">{\displaystyle a_{23}}</annotation>
  </semantics>
</math></span><img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/e214e4d1b4dcc0f3909e915fd69012c5bd1b7b7b" class="mwe-math-fallback-image-inline" aria-hidden="true" style="vertical-align: -0.671ex; width:3.106ex; height:2.009ex;" alt="{\displaystyle a_{23}}"></span>
</td></tr></tbody></table></div>

In [15]:
import numpy as np 

In [16]:

a = np.array([1,2,3,4,5,6,7,8,9]) 
print(a)
print('\n')
b = np.array([[1,2,3,4],[5,6,7,8]]) 


print(b)



[1 2 3 4 5 6 7 8 9]


[[1 2 3 4]
 [5 6 7 8]]


if we have a multi dementional array :

[[1,2,3],

[4,5,6],

[7,8,9]]

row 1 : 1,4,7 , row 2 : 2,5,8 , row 3 : 3,6,9

col 1 : 1,2,3 , col 3 : 4,5,6 , col 3 : 7,8,9

In [17]:
# minimum dimensions i.e. ndmin
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 4) 
print(a)

[[[[1 2 3 4 5]]]]


<h3>NumPy - Data Types</h3><br>
NumPy supports a much greater variety of numerical types than Python does.

NumPy numerical types are instances of dtype (data-type) objects, each having unique characteristics. The dtypes are available as np.bool_, np.float32, etc.

<b>numpy.dtype(object, align, copy)</b>

The parameters are −

Object − To be converted to data type object

Align − If true, adds padding to the field to make it similar to C-struct

Copy − Makes a new copy of dtype object. If false, the result is reference to builtin data type object

--------

Each built-in data type has a character code that uniquely identifies it.

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

In [38]:
student = np.dtype([('name','S20'), ('age', 'i'), ('marks', 'f')]) 

# S20 means a string with max 20 characters

a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a)
print (a['age'])

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]
[21 18]


<h3>NumPy - Array Attributes</h3>



<h5>ndarray.shape

In [42]:
a = np.array([[1,2,3],[4,5,6]]) 
print(a.shape) #returns a tuple

b = a.reshape(3,2) 
print(b)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


<h5>ndarray.ndim

In [51]:
a = np.arange(15) 
print(a.ndim ) # returns the number of array dimensions i.e. one in this case
print(a)

b = a.reshape(3,5) 
print(b.ndim)
print(b)

1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
2
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


<h5>numpy.itemsize</h5>
This array attribute returns the length of each element of array in bytes.

a.itemsize


<h5>numpy.flags</h5>
<table class="table table-bordered">
<tbody><tr>

<th style="text-align:center;">Attribute &amp; Description</th>
</tr>
<tr>

<td><p><b>C_CONTIGUOUS (C)</b></p>
<p>The data is in a single, C-style contiguous segment</p>
</td>
</tr>
<tr>

<td><p><b>F_CONTIGUOUS (F)</b></p>
<p>The data is in a single, Fortran-style contiguous segment</p>
</td>
</tr>
<tr>

<td><p><b>OWNDATA (O)</b></p>
<p>The array owns the memory it uses or borrows it from another object</p>
</td>
</tr>
<tr>

<td><p><b>WRITEABLE (W)</b></p>
<p>The data area can be written to. Setting this to False locks the data, making it read-only</p>
</td>
</tr>
<tr>

<td><p><b>ALIGNED (A)</b></p>
<p>The data and all elements are aligned appropriately for the hardware</p>
</td>
</tr>
<tr>

<td><p><b>UPDATEIFCOPY (U)</b></p>
<p>This array is a copy of some other array. When this array is deallocated, the base array will be updated with the contents of this array</p>
</td>
</tr>
</tbody></table>

In [55]:
a = np.arange(15).reshape(3,5)
print(a)
print(a.flags)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


<h3>NumPy - Array Creation Routines</h3>

<h5>numpy.empty</h5>

numpy.empty(shape, dtype = float, order = 'C')

<h5>numpy.zeros</h5>

numpy.zeros(shape, dtype = float, order = 'C')

<h5>numpy.ones</h5>

numpy.ones(shape, dtype = None, order = 'C')

Order

'C' for C-style row-major array, 'F' for FORTRAN style column-major array

In [67]:
a = np.empty([2,2])
b = np.zeros([3,5])
c = np.ones([3,4,5])

print(a)
print('\n')
print(b)
print('\n')
print(c)


[[9.60071790e-251 9.26319189e+303]
 [1.16848223e+304 1.40958277e-315]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


<h3>NumPy - Array From Existing Data</h3>

<h5>numpy.asarray</h5>

This function is similar to numpy.array except for the fact that it has fewer parameters. This routine is useful for converting Python sequence into ndarray.

a - Input data in any form such as list, list of tuples, tuples, tuple of tuples or tuple of lists



In [68]:
lis = [1,2,3,4,5]
a = np.asarray(lis)
print(a)

[1 2 3 4 5]


<h3>NumPy - Array From Numerical Ranges</h3>

<h5>numpy.arange</h5>

ndarray object containing evenly spaced values within a given range.

numpy.arange(start, stop, step, dtype)

start - The start of an interval. If omitted, defaults to 0
stop - The end of an interval (not including this number)
step - Spacing between values, default is 1

In [71]:
a = np.arange(2,20,5)
print(a)

[ 2  7 12 17]


<h5>numpy.linspace</h5>

numpy.linspace(start, stop, num, endpoint, retstep, dtype)

<table class="table table-bordered">
<tbody><tr>

<th style="text-align:center;">Parameter &amp; Description</th>
</tr>
<tr>

<td><p><b>start</b></p>
<p>The starting value of the sequence</p>
</td>
</tr>
<tr>

<td><p><b>stop</b></p>
<p>The end value of the sequence, included in the sequence if endpoint set to true</p>
</td>
</tr>
<tr>

<td><p><b>num</b></p>
<p>The number of evenly spaced samples to be generated. Default is 50</p>
</td>
</tr>
<tr>

<td><p><b>endpoint</b></p>
<p>True by default, hence the stop value is included in the sequence. If false, it is not included</p>
</td>
</tr>
<tr>

<td><p><b>retstep</b></p>
<p>If true, returns samples and step between the consecutive numbers</p>
</td>
</tr>
<tr>

<td><p><b>dtype</b></p>
<p>Data type of output <b>ndarray</b></p>
</td>
</tr>
</tbody></table>

In [81]:
a = np.linspace(5,20,4)
print(a)

a = np.linspace(5,20,4,endpoint = False)
print(a)

a = np.linspace(5,20,4,retstep = True)
print(a)

[ 5. 10. 15. 20.]
[ 5.    8.75 12.5  16.25]
(array([ 5., 10., 15., 20.]), 5.0)


<h3>NumPy - Indexing & Slicing</h3>

slice object is constructed by giving start, stop, and step parameters

In [103]:
a = (np.arange(1,10))

b = slice(0,5,2)

print(a)
print('\n')
print(a[b])
print('\n')

# shorthand notation more preferred
c = a[0:5:2]
print(c)

c = a[5]
print((c))

c = a[2:8]
print(c)


[1 2 3 4 5 6 7 8 9]


[1 3 5]


[1 3 5]
6
[3 4 5 6 7 8]


In [120]:
# multidimentional arrays
a = (np.arange(1,10)).reshape(3,3)
print(a)
print('\n')

c = a[1:,]
print(c)
print('\n')
c = a[...,1:]
print(c)
print('\n')
# ... means everything in that row/column can be replaced by 0:
c = a[1,0:2]
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[4 5 6]
 [7 8 9]]


[[2 3]
 [5 6]
 [8 9]]


[4 5]


<h5>Boolean Array Indexing

In [128]:
print(a)
print()
print (a[a > 5])
print(a[~(a > 5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[6 7 8 9]
[1 2 3 4 5]


<h3>NumPy - Broadcasting</h3>

The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations.

In [132]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print(c)
print()

b = [[0,0,0,0],[10,20,30,40],[20,30,40,50]]
c = a + b
print(c)
print()



[ 10  40  90 160]

[[ 1  2  3  4]
 [11 22 33 44]
 [21 32 43 54]]



<h3>NumPy - Iterating Over Array</h3>

iterator object numpy.nditer

In [158]:
a = (np.arange(1,10)).reshape(3,3)
print(a)
print()

# end = '' in a print statement is default \n so we change it to ' ' to make the next print continue in the same line
for x in np.nditer(a):
    print(x,end="  ")


[[1 2 3]
 [4 5 6]
 [7 8 9]]

1  2  3  4  5  6  7  8  9  

<h5>Changing the order of the matrix will change the itterator object to itterate in a row-major or a column-major style</h5>

In [164]:

for x in np.nditer(a,order = 'C'):
    print(x,end ='  ')
print()
for x in np.nditer(a,order = 'F'):
    print(x,end ='  ')

[1 2 3 4 5 6 7 8 9]  
1  4  7  2  5  8  3  6  9  

In [165]:
for x in np.nditer(a, flags = ['external_loop'] ,order = 'F'):
    print(x, end = '  ')

[1 4 7]  [2 5 8]  [3 6 9]  

<h5>Broadcasting Iteration</h5>

In [172]:
print(a, end = '\n\n')
b = (np.arange(10,100,10)).reshape(3,3)
print(b , end = '\n\n')
for x,y in np.nditer([a,b]): 
    print(x+y, end ='   '),

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[10 20 30]
 [40 50 60]
 [70 80 90]]

11   22   33   44   55   66   77   88   99   

<h3>NumPy - Array Manipulation</h3>

<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;">Sr.No.</th>
<th style="text-align:center;">Shape &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><a href="/numpy/numpy_reshape.htm">reshape</a>
<p>Gives a new shape to an array without changing its data</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><a href="/numpy/numpy_ndarray_flat.htm">flat</a>
<p>A 1-D iterator over the array</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><a href="/numpy/numpy_ndarray_flatten.htm">flatten</a>
<p>Returns a copy of the array collapsed into one dimension</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><a href="/numpy/numpy_ndarray_ravel.htm">ravel</a>
<p>Returns a contiguous flattened array</p>
</td>
</tr>
</tbody></table>


<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;">Sr.No.</th>
<th style="text-align:center;">Operation &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><a href="/numpy/numpy_transpose.htm">transpose</a>
<p>Permutes the dimensions of an array</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><a href="/numpy/numpy_ndarray_t.htm">ndarray.T</a>
<p>Same as self.transpose()</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><a href="/numpy/numpy_rollaxis.htm">rollaxis</a>
<p>Rolls the specified axis backwards</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><a href="/numpy/numpy_swapaxes.htm">swapaxes</a>
<p>Interchanges the two axes of an array</p>
</td>
</tr>
</tbody></table>


<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;">Sr.No.</th>
<th style="text-align:center;">Dimension &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><a href="/numpy/numpy_broadcast.htm">broadcast</a>
<p>Produces an object that mimics broadcasting</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><a href="/numpy/numpy_broadcast_to.htm">broadcast_to</a>
<p>Broadcasts an array to a new shape</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><a href="/numpy/numpy_expand_dims.htm">expand_dims</a>
<p>Expands the shape of an array</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><a href="/numpy/numpy_squeeze.htm">squeeze</a>
<p>Removes single-dimensional entries from the shape of an array</p>
</td>
</tr>
</tbody></table>


<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;">Sr.No.</th>
<th style="text-align:center;">Array &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><a href="/numpy/numpy_concatenate.htm">concatenate</a>
<p>Joins a sequence of arrays along an existing axis</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><a href="/numpy/numpy_stack.htm">stack</a>
<p>Joins a sequence of arrays along a new axis</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><a href="/numpy/numpy_hstack.htm">hstack</a>
<p>Stacks arrays in sequence horizontally (column wise)</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><a href="/numpy/numpy_vstack.htm">vstack</a>
<p>Stacks arrays in sequence vertically (row wise)</p>
</td>
</tr>
</tbody></table>
<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;">Sr.No.</th>
<th style="text-align:center;">Array &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><a href="/numpy/numpy_split.htm">split</a>
<p>Splits an array into multiple sub-arrays</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><a href="/numpy/numpy_hsplit.htm">hsplit</a>
<p>Splits an array into multiple sub-arrays horizontally (column-wise)</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><a href="/numpy/numpy_vsplit.htm">vsplit</a>
<p>Splits an array into multiple sub-arrays vertically (row-wise)</p>
</td>
</tr>
</tbody></table>

<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center; width:10%;">Sr.No.</th>
<th style="text-align:center;">Element &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><a href="/numpy/numpy_resize.htm">resize</a>
<p>Returns a new array with the specified shape</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><a href="/numpy/numpy_append.htm">append</a>
<p>Appends the values to the end of an array</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><a href="/numpy/numpy_insert.htm">insert</a>
<p>Inserts the values along the given axis before the given indices</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><a href="/numpy/numpy_delete.htm">delete</a>
<p>Returns a new array with sub-arrays along an axis deleted</p>
</td>
</tr>
<tr>
<td class="ts">5</td>
<td><a href="/numpy/numpy_unique.htm">unique</a>
<p>Finds the unique elements of an array</p>
</td>
</tr>
</tbody></table>

<h3> Math and Statistical Functions:</h3>


------------
numpy.floor(nparray)


numpy.ceil(nparray)


numpy.add(nparray)


numpy.subtract(nparray)


numpy.multuply(nparray)


numpy.divide(nparray)


numpy.power(nparray,nparray)

---------


numpy.amin(nparray,axis=0)


numpy.amax(nparray,axis=0)


<u>axis is optional, </u>

if not used the functions returns man/mi from the entile array 

if used ( 0 - row-wise , 1 - column-wise ) then it will give max/min of eachrow/column


numpy.argmax() and numpy.argmin() - functions that return the indices of the max/min in an array


---------


numpy.percentile(nparray,range,axis)

<u>range and axis is optional</u>

range - the range in which your percentile would lie, default: 0-100


---------



numpy.median(nparray,axis=0)

numpy.mean(nparray,axis=0)

numpy.average(nparray,axis=0)

numpy.std(nparray,axis=0)

numpy.var(nparray,axis=0)



<h3>Sort, Search And Counting Functions</h3>

-------


numpy.sort(a, axis, kind, order)

kind - ‘quicksort’ , ‘mergesort’ , ‘heapsort’  -  default: ‘quicksort’

order - If the array contains fields, the order of fields to be sorted (i.e. once set in dtype)

-------


numpy.nonzero(nparray,axis=0)


The numpy.nonzero() function returns the indices of non-zero elements in the input array.


-------


numpy.extract(condition, nparray)


The extract() function returns the elements satisfying any condition.



<h3>NumPy - Copies And Views</h3>


<b>No Copy

In [179]:
a = [1,2,3,4,5]
b = a
b[4] = 99
print(a)
print(b)

[1, 2, 3, 4, 99]
[1, 2, 3, 4, 99]


<b>Shallow copy

In [183]:
a = [1,2,3,4,5]
b = a[:]
b[4] = 99
print(a)
print(b)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 99]


<b>Deep copy

In [182]:
a = [1,2,3,4,5]
b = a.copy() 
b[4] = 99
print(a)
print(b)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 99]


~ <b>Difference between Shallow and Deep copy:</b>


if an array is a multidimentional array than shallow copy will only copy the outer list whereas referance the inner lists whereas deep copy will copy everything(no references)



<h3>NumPy - Linear Algebra</h3>


<table class="table table-bordered">
<tbody><tr>
<th style="text-align:center;width:10%">Sr.No.</th>
<th style="text-align:center;">Function &amp; Description</th>
</tr>
<tr>
<td class="ts">1</td>
<td><a href="/numpy/numpy_dot.htm">dot</a>
<p>Dot product of the two arrays</p>
</td>
</tr>
<tr>
<td class="ts">2</td>
<td><a href="/numpy/numpy_vdot.htm">vdot</a>
<p>Dot product of the two vectors</p>
</td>
</tr>
<tr>
<td class="ts">3</td>
<td><a href="/numpy/numpy_inner.htm">inner</a>
<p>Inner product of the two arrays</p>
</td>
</tr>
<tr>
<td class="ts">4</td>
<td><a href="/numpy/numpy_matmul.htm">matmul</a>
<p>Matrix product of the two arrays</p>
</td>
</tr>
<tr>
<td class="ts">5</td>
<td><a href="/numpy/numpy_determinant.htm">determinant</a>
<p>Computes the determinant of the array</p>
</td>
</tr>
<tr>
<td class="ts">6</td>
<td><a href="/numpy/numpy_solve.htm">solve</a>
<p>Solves the linear matrix equation</p>
</td>
</tr>
<tr>
<td class="ts">7</td>
<td><a href="/numpy/numpy_inv.htm">inv</a>
<p>Finds the multiplicative inverse of the matrix</p>
</td>
</tr>
</tbody></table>

<h3>I/O with NumPy</h3>

numpy.save() file stores the input array in a disk file with npy extension.

numpy.load('filename.npy') 

svaing data as .txt:

np.savetxt('out.txt',a) 

b = np.loadtxt('out.txt') 

<h3>References</h3>

 - https://www.tutorialspoint.com/
 
 - https://www.wikipedia.org
 
 - https://stackoverflow.com